services:
  viewer_three_panorama_to_tile:
    container_name: three_panorama_to_tile
    build: .
    volumes:
      - "./app/:/app/"
    command: "python index.py --path ./assets/panoramas/ --results_path ./results/t/ --levels 3 --initial_quality 1"
